import time
name = input("What is your name traveller? ")
print("Hello " + str(name) + ". Welcome to the land of Austeen. Your journey is about to begin. ")
time.sleep(2)
print("You travel along Shoal Creek, approaching the deep dark RoyAnn Forest.")
time.sleep(2)
print("At the head of the Creek, you reach a fork in the road.")
time.sleep(2)
print("To the left lies an open field skirting around the forest.")
time.sleep(2)
print("To the right lies the forest, from which a dark presence appears to be emanating.")
time.sleep(2)
print("Which path will you take " + str(name) + "?")
choice1 = input("Enter L or R: ")
choice1 = choice1.upper()
choice1 = choice1.strip()
if choice1 == "L":
    time.sleep(2)
    print("Being a weak traveller with poor lineage, you choose the open field.")
    time.sleep(2)
    print("You step out into the grass, and a sweet breeze washes over you.")
    time.sleep(2)
    print("Perhaps the naysayers in your village were wrong, and your travels will not lead to an early grave.")
    time.sleep(2)
    print("At that moment, a ludicrously oversized grackle falls from the sky, gobbling you up in one gulp.")
    time.sleep(2)
    print("'It's the great Grackle!' you shriek, your voice dopplering as you dissapear down the great Grackle's gullet.")
    time.sleep(2)
    print("'Thank goodness for fearful weaklings', the Grackle declares over a loud burp.")
    time.sleep(2)
    print("T H E  E N D")
if choice1 == "R":
    time.sleep(2)
    print("Feeling brave, you steel yourself and enter the forest.")
    time.sleep(2)
    print("You walk for hours through the murky shade of the trees, passing all manner of horrors creeping about in the shadows")
    time.sleep(2)
    print("As hunger begins to sap your strength, you happen upon the fabled field of Zil-kor.")
    time.sleep(2)
    print("You see plump rabbits frolicking amongst the wildflowers.")
    time.sleep(2)
    print("Drooling with anticipation, you ready your bow and step out of the treeline.")
    time.sleep(2)
    print("At that moment, an enormous Grackle drops from the sky.")
    time.sleep(2)
    print("'Wait a second'")
    time.sleep(2)
    print("'Isn't this is meant to be the good ending?' you cry.")
    time.sleep(2)
    print("'Everyone's a critic these days...' the Grackle complains as it swallows you whole.")
    time.sleep(2)
    print("The last thing you hear is the laughter of the Rabbits.")
    time.sleep(2)
    print("That's what being brave gets you!")
    time.sleep(2)
    print("T H E  E N D")
elif choice1 != "L" and choice1 != "R":
    time.sleep(2)
    print("Not good at following directions, are you? You don't get to play.")
    time.sleep(2)
    print("T H E  E N D. Boo.")